"""Independent stoichiometric expectations, never generated by the implementation."""
import copy
import json
import unittest

from petrolab.mica_formula import calculate_mica


def measurements(composition):
    return [{'measurement_id': f'm-{field}', 'field': field, 'raw_token': str(value),
             'unit': 'wt.%', 'value_status': 'numeric', 'qualifier': None,
             'reported_fe_form': field if field.startswith('Fe') else None}
            for field, value in composition.items()]


def phlogopite():
    # Independent oxide formula masses; one mole KMg3AlSi3O10(OH)2 weighs 417.254 g.
    # Water is not an input to the 22-charge method. The oxide sum is below 100%.
    return {'SiO2': 3 * 60.083 / 417.254 * 100,
            'Al2O3': 0.5 * 101.961 / 417.254 * 100,
            'MgO': 3 * 40.304 / 417.254 * 100,
            'K2O': 0.5 * 94.195 / 417.254 * 100, 'FeO': 0}


def run(composition, fe_mode='all_fe2', oh_mode='not_calculated'):
    return calculate_mica(measurements(composition), fe_mode,
                          anion_basis='ideal_O10_W2', oh_mode=oh_mode)


class MicaFormulaTests(unittest.TestCase):
    def assert_current(self, result, expected):
        self.assertEqual(result['status'], 'current', result['errors'])
        for field, value in expected.items():
            self.assertAlmostEqual(result['values'][field], value, places=12)
        json.dumps(result, allow_nan=False)

    def test_independent_phlogopite(self):
        source = measurements(phlogopite())
        before = copy.deepcopy(source)
        result = calculate_mica(source, 'all_fe2', anion_basis='ideal_O10_W2', oh_mode='not_calculated')
        self.assert_current(result, {'Si_apfu': 3, 'Al_apfu': 1, 'Mg_apfu': 3,
                                     'K_apfu': 1, 'Fe2_apfu': 0, 'cation_sum': 8})
        self.assertEqual(source, before)
        self.assertLess(result['values']['oxide_total'], 100)
        self.assertNotIn('OH_est_apfu', result['values'])
        self.assertNotIn('Fe3_apfu', result['values'])
        self.assertNotIn('Li_apfu', result['values'])
        self.assertIn('Li2O', result['unmeasured'])
        self.assertEqual(result['method_status'], 'draft')

    def test_published_mashhad_g1_biotite_mean(self):
        # Shabani, Masoudi & Tecce (2010), J. Sci. I. R. Iran 21(4),
        # Table 2, mean of 56 natural G1 biotite analyses. The paper reports
        # cations on a doubled 22-oxygen basis; published values below are
        # divided by two to compare with this method's O10W2 formula unit.
        composition = {
            'SiO2': 36.22, 'TiO2': 2.88, 'Al2O3': 16.27,
            'Fe2O3': 5.08, 'FeO': 15.61, 'MnO': 0.59,
            'MgO': 9.66, 'BaO': 0.26, 'CaO': 0.07,
            'Na2O': 0.08, 'K2O': 9.34, 'F': 0.76, 'Cl': 0.01,
        }
        expected = {
            'Si_apfu': 5.48 / 2,
            'Al_apfu': (2.52 + 0.38) / 2,
            'Ti_apfu': 0.33 / 2,
            'Fe3_apfu': 0.58 / 2,
            'Fe2_apfu': 1.97 / 2,
            'Mn_apfu': 0.08 / 2,
            'Mg_apfu': 2.18 / 2,
            'Ba_apfu': 0.02 / 2,
            'Ca_apfu': 0.01 / 2,
            'Na_apfu': 0.02 / 2,
            'K_apfu': 1.80 / 2,
            'F_apfu': 0.36 / 2,
            'Cl_apfu': 0.00 / 2,
        }
        result = run(composition, 'reported_split')
        self.assertEqual(result['status'], 'current', result['errors'])
        for field, published in expected.items():
            with self.subTest(field=field):
                # The source table is rounded to 0.01 on its doubled basis.
                self.assertAlmostEqual(result['values'][field], published, delta=0.006)
        self.assertNotIn('OH_est_apfu', result['values'])

    def test_independent_annite_and_muscovite(self):
        annite = {'SiO2': 3 * 60.083, 'Al2O3': 0.5 * 101.961, 'MgO': 0,
                  'K2O': 0.5 * 94.195, 'FeO': 3 * 71.844}
        muscovite = {**annite, 'Al2O3': 1.5 * 101.961, 'FeO': 0}
        for composition, expected in [(annite, {'Fe2_apfu': 3, 'Al_apfu': 1, 'cation_sum': 8}),
                                      (muscovite, {'Fe2_apfu': 0, 'Al_apfu': 3, 'cation_sum': 7})]:
            # Scale oxide masses to an arbitrary common weight basis, independent of core.
            total = sum(composition.values()) + 18.015
            with self.subTest(expected=expected):
                result = run({k: v / total * 100 for k, v in composition.items()})
                self.assert_current(result, {**expected, 'Si_apfu': 3, 'K_apfu': 1, 'Mg_apfu': 0})

    def test_ti_ferric_mica_charge_balance_without_inferred_sites(self):
        # K Mg2 Fe2+.25 Fe3+.5 Ti.25 Al2 Si2: 1+4+.5+1.5+1+6+8 = 22.
        weights = {'SiO2': 2 * 60.083, 'Al2O3': 101.961, 'MgO': 2 * 40.304,
                   'K2O': .5 * 94.195, 'FeO': .25 * 71.844,
                   'Fe2O3': .25 * 159.687, 'TiO2': .25 * 79.865}
        total = sum(weights.values()) + 18.015
        result = run({k: v / total * 100 for k, v in weights.items()}, 'reported_split')
        self.assert_current(result, {'Si_apfu': 2, 'Al_apfu': 2, 'Mg_apfu': 2,
                                     'Fe2_apfu': .25, 'Fe3_apfu': .5, 'Ti_apfu': .25,
                                     'K_apfu': 1, 'cation_sum': 8})
        self.assertNotIn('vacancy', result['values'])
        self.assertNotIn('Al_IV', result['values'])

    def test_fluorophlogopite_does_not_change_cation_charge_basis(self):
        result = run({**phlogopite(), 'F': 2 * 18.998 / 417.254 * 100, 'Cl': 0},
                     oh_mode='ideal_2_minus_f_cl')
        self.assert_current(result, {'Si_apfu': 3, 'Mg_apfu': 3, 'F_apfu': 2,
                                     'Cl_apfu': 0, 'OH_est_apfu': 0, 'cation_sum': 8})
        self.assertIn('m-F', result['OH_est_basis']['input_measurement_ids'])
        self.assertIn('m-SiO2', result['OH_est_basis']['input_measurement_ids'])
        self.assertEqual(result['OH_est_basis']['formula'], '2 - F_apfu - Cl_apfu')

    def test_mixed_halogens_and_explicit_zero_are_distinct_from_absence(self):
        result = run({**phlogopite(), 'F': .5 * 18.998 / 417.254 * 100,
                      'Cl': .25 * 35.45 / 417.254 * 100}, oh_mode='ideal_2_minus_f_cl')
        self.assert_current(result, {'F_apfu': .5, 'Cl_apfu': .25, 'OH_est_apfu': 1.25})
        self.assert_current(run({**phlogopite(), 'F': 0, 'Cl': 0}, oh_mode='ideal_2_minus_f_cl'),
                            {'OH_est_apfu': 2})
        missing = run({**phlogopite(), 'F': 0}, oh_mode='ideal_2_minus_f_cl')
        self.assertEqual(missing['status'], 'failed')
        self.assertTrue(any('Cl:' in error for error in missing['errors']))
        self.assertEqual(missing['values'], {})
        self.assertNotIn('OH_est_apfu', run({**phlogopite(), 'F': 0})['values'])

    def test_overfilled_halogen_group_never_produces_negative_oh(self):
        composition = {**phlogopite(), 'F': 2.1 * 18.998 / 417.254 * 100, 'Cl': 0}
        for mode in ('not_calculated', 'ideal_2_minus_f_cl'):
            with self.subTest(mode=mode):
                result = run(composition, oh_mode=mode)
                self.assertEqual(result['status'], 'failed')
                self.assertEqual(result['values'], {})
                self.assertTrue(any('2 APFU' in error for error in result['errors']))

    def test_parameters_are_explicit(self):
        source = measurements(phlogopite())
        for fe, basis, oh in [(None, 'ideal_O10_W2', 'not_calculated'),
                              ([], 'ideal_O10_W2', 'not_calculated'),
                              ('all_fe2', '22_plus_z', 'not_calculated'),
                              ('all_fe2', None, 'not_calculated'),
                              ('all_fe2', 'ideal_O10_W2', None)]:
            with self.subTest(fe=fe, basis=basis, oh=oh):
                self.assertEqual(calculate_mica(source, fe, anion_basis=basis, oh_mode=oh)['status'], 'failed')

    def test_ima_calculation_basis_boundary_does_not_guess_h2o_or_oxidation(self):
        # Rieder et al. (1999), Mineralogical Magazine 63(2), pp. 268–269:
        # measured H2O, idealized 22 charges and oxidation/deprotonation 22+z
        # are distinct calculations, not interchangeable parameter labels.
        source = measurements({**phlogopite(), 'Fe2O3': 0})
        before = copy.deepcopy(source)
        ideal = calculate_mica(source, 'reported_split', anion_basis='ideal_O10_W2',
                               oh_mode='not_calculated')
        self.assertEqual(ideal['status'], 'current', ideal['errors'])
        oxidized = calculate_mica(source, 'reported_split', anion_basis='22_plus_z',
                                  oh_mode='not_calculated')
        self.assertEqual(oxidized['status'], 'failed')
        self.assertEqual(oxidized['values'], {})
        self.assertTrue(any('22+z' in error for error in oxidized['errors']))
        with_water = calculate_mica([*source, *measurements({'H2O': 1})], 'reported_split',
                                    anion_basis='ideal_O10_W2', oh_mode='not_calculated')
        self.assertEqual(with_water['status'], 'failed')
        self.assertEqual(with_water['values'], {})
        self.assertTrue(any('H2O' in error for error in with_water['errors']))
        self.assertEqual(source, before)

    def test_total_iron_is_not_measured_split_iron(self):
        total = phlogopite()
        total['FeOt'] = total.pop('FeO')
        self.assert_current(run(total), {'Fe2_apfu': 0, 'Mg_apfu': 3})
        for composition, mode in [({**phlogopite(), 'FeOt': 0}, 'all_fe2'),
                                  ({**phlogopite(), 'Fe2O3': 0}, 'all_fe2'),
                                  ({**total, 'Fe2O3': 0}, 'reported_split'),
                                  (phlogopite(), 'reported_split')]:
            self.assertEqual(run(composition, mode)['status'], 'failed')
        for form in ('FeOt', 'Fe2O3t', 'unresolved'):
            source = measurements({**phlogopite(), 'Fe2O3': 0})
            next(m for m in source if m['field'] == 'FeO')['reported_fe_form'] = form
            result = calculate_mica(source, 'reported_split', anion_basis='ideal_O10_W2', oh_mode='not_calculated')
            self.assertEqual(result['status'], 'failed')

    def test_invalid_values_units_states_and_duplicates(self):
        changes = [{'raw_token': v} for v in ('-1', 'NaN', 'inf', 'abc', None)]
        changes += [{'unit': 'ppm'}, {'value_status': 'missing'}, {'qualifier': '<'}]
        for field in ('SiO2', 'MgO', 'F'):
            for change in changes:
                source = measurements({**phlogopite(), 'F': 0})
                next(m for m in source if m['field'] == field).update(change)
                with self.subTest(field=field, change=change):
                    result = calculate_mica(source, 'all_fe2', anion_basis='ideal_O10_W2', oh_mode='not_calculated')
                    self.assertEqual(result['status'], 'failed')
                    self.assertEqual(result['values'], {})
        source = measurements(phlogopite())
        source.append(dict(source[0]))
        self.assertEqual(calculate_mica(source, 'all_fe2', anion_basis='ideal_O10_W2',
                                       oh_mode='not_calculated')['status'], 'failed')
        self.assertEqual(run({**phlogopite(), 'SiO2': 0})['status'], 'failed')
        for field in ('MgO', 'Al2O3', 'K2O'):
            composition = phlogopite()
            del composition[field]
            self.assertEqual(run(composition)['status'], 'failed')

    def test_h2o_and_unknown_weight_components_are_not_silently_discarded(self):
        for field in ('H2O', 'P2O5', 'Fe2O3t', 'Unknown'):
            with self.subTest(field=field):
                self.assertEqual(run({**phlogopite(), field: 0})['status'], 'failed')
        source = measurements(phlogopite())
        source.append({'field': 'Rb', 'unit': 'ppm', 'raw_token': '100',
                       'value_status': 'numeric', 'measurement_id': 'trace-rb'})
        result = calculate_mica(source, 'all_fe2', anion_basis='ideal_O10_W2', oh_mode='not_calculated')
        self.assert_current(result, {'Mg_apfu': 3})
        self.assertEqual(result['excluded'][0]['measurement_id'], 'trace-rb')
        self.assertNotIn('trace-rb', [m['measurement_id'] for m in result['used']])

    def test_scale_invariance_and_nonfinite_outputs_are_rejected(self):
        for scale in (0.01, 2):
            self.assert_current(run({k: v * scale for k, v in phlogopite().items()}),
                                {'Si_apfu': 3, 'Mg_apfu': 3})
        huge = run({k: 1e308 for k in phlogopite()})
        self.assertEqual(huge['status'], 'failed')
        tiny = run({**{k: 1e-310 for k in phlogopite()}, 'F': 1e308})
        self.assertEqual(tiny['status'], 'failed')
        json.dumps(tiny, allow_nan=False)


if __name__ == '__main__':
    unittest.main()
