"""Independent stoichiometric and published expectations for draft Cpx 6 O."""
import copy
import json
import unittest

from petrolab.clinopyroxene_formula import calculate_clinopyroxene


def measurements(composition):
    return [{'measurement_id': f'm-{field}', 'field': field, 'raw_token': str(value),
             'unit': 'wt.%', 'value_status': 'numeric', 'qualifier': None,
             'reported_fe_form': field if field.startswith('Fe') else None}
            for field, value in composition.items()]


def run(composition, fe_mode='all_fe2'):
    return calculate_clinopyroxene(measurements(composition), fe_mode)


class ClinopyroxeneFormulaTests(unittest.TestCase):
    def test_ideal_diopside_hedenbergite_and_equal_mix(self):
        # Independent oxide masses for Ca(Mg,Fe)Si2O6; no production code in expectations.
        for mg, fe, expected in [(40.304, 0, (0, 50, 50)),
                                 (0, 71.844, (50, 0, 50)),
                                 (20.152, 35.922, (25, 25, 50))]:
            with self.subTest(mg=mg, fe=fe):
                composition = {'SiO2': 2 * 60.083, 'CaO': 56.077, 'MgO': mg, 'FeO': fe}
                source = measurements(composition)
                before = copy.deepcopy(source)
                result = calculate_clinopyroxene(source, 'all_fe2')
                self.assertEqual(result['status'], 'current', result['errors'])
                self.assertAlmostEqual(result['values']['Si_apfu'], 2, places=12)
                self.assertAlmostEqual(result['values']['Ca_apfu'], 1, places=12)
                self.assertAlmostEqual(result['values']['Mg_apfu'], mg / 40.304, places=12)
                self.assertAlmostEqual(result['values']['Fe2_apfu'], fe / 71.844, places=12)
                self.assertAlmostEqual(result['values']['Wo'], expected[2], places=12)
                self.assertAlmostEqual(result['values']['En'], expected[1], places=12)
                self.assertAlmostEqual(result['values']['Fs'], expected[0], places=12)
                self.assertEqual(result['method_status'], 'draft')
                self.assertEqual(source, before)
                json.dumps(result, allow_nan=False)

    def test_published_experimental_e16_085_clinopyroxene(self):
        # Journal of Petrology 63(11), egac110 (2022), Table 6, E16–085 Cpx (n=1).
        # Published oxide wt.% and cations/6 O, not generated by the implementation.
        composition = {'SiO2': 50.00, 'TiO2': .48, 'Al2O3': 8.39,
                       'Cr2O3': .62, 'FeO': 5.78, 'MgO': 19.00,
                       'CaO': 14.79, 'Na2O': .20, 'K2O': .02}
        published = {'Si_apfu': 1.81, 'Ti_apfu': .01, 'Al_apfu': .36,
                     'Cr_apfu': .02, 'Fe2_apfu': .18, 'Mg_apfu': 1.03,
                     'Ca_apfu': .57, 'Na_apfu': .01,
                     'cation_sum': 3.99, 'Wo': 32.34, 'En': 57.79, 'Fs': 9.87}
        result = run(composition)
        self.assertEqual(result['status'], 'current', result['errors'])
        for field, value in published.items():
            with self.subTest(field=field):
                self.assertAlmostEqual(result['values'][field], value,
                                       delta=.011 if field.endswith('_apfu') or field == 'cation_sum' else .03)
        self.assertEqual(result['values']['oxide_total'], 99.28)

    def test_iron_modes_and_unknown_iron_do_not_infer_fe3(self):
        baseline = {'SiO2': 120.166, 'CaO': 56.077, 'MgO': 40.304, 'FeO': 0}
        self.assertEqual(run(baseline)['status'], 'current')
        self.assertNotIn('Fe3_apfu', run(baseline)['values'])
        split = {**baseline, 'Fe2O3': 0}
        self.assertEqual(run(split, 'reported_split')['status'], 'current')
        for composition, mode in [(split, 'all_fe2'), (baseline, 'reported_split'),
                                  ({**baseline, 'FeOt': 0}, 'all_fe2'),
                                  ({**baseline, 'Fe2O3t': 0}, 'reported_split')]:
            with self.subTest(composition=composition, mode=mode):
                self.assertEqual(run(composition, mode)['status'], 'failed')
        source = measurements(split)
        next(m for m in source if m['field'] == 'FeO')['reported_fe_form'] = 'FeOt'
        self.assertEqual(calculate_clinopyroxene(source, 'reported_split')['status'], 'failed')

    def test_missing_censored_invalid_and_out_of_domain_inputs(self):
        baseline = {'SiO2': 120.166, 'CaO': 56.077, 'MgO': 40.304, 'FeO': 0}
        for field in ('SiO2', 'CaO', 'MgO', 'FeO'):
            composition = dict(baseline)
            del composition[field]
            self.assertEqual(run(composition)['status'], 'failed')
        for change in ({'raw_token': '<0.1', 'value_status': 'below_detection_limit'},
                       {'raw_token': None, 'value_status': 'missing'}, {'unit': 'ppm'},
                       {'raw_token': 'NaN'}, {'raw_token': '-1'}):
            source = measurements(baseline)
            source[0].update(change)
            self.assertEqual(calculate_clinopyroxene(source, 'all_fe2')['status'], 'failed')
        self.assertEqual(run({**baseline, 'H2O': 0})['status'], 'failed')
        self.assertEqual(run({**baseline, 'P2O5': 0})['status'], 'failed')
        self.assertEqual(run({**baseline, 'SiO2': 0})['status'], 'failed')
        source = measurements(baseline)
        source.append({'measurement_id': 'trace-rb', 'field': 'Rb', 'raw_token': '100',
                       'unit': 'ppm', 'value_status': 'numeric'})
        result = calculate_clinopyroxene(source, 'all_fe2')
        self.assertEqual(result['status'], 'current', result['errors'])
        self.assertEqual(result['excluded'][0]['measurement_id'], 'trace-rb')
        self.assertNotIn('trace-rb', [item['measurement_id'] for item in result['used']])


if __name__ == '__main__':
    unittest.main()
