// Synthetic UI-only fixture. Responses were generated by real Python; no project is written here.
import React from 'react';
import { createRoot } from 'react-dom/client';
import { MineralsWorkspace } from '../src/MineralsWorkspace';
import data from './formula-browser-data.json';
import '../src/styles.css';

let runs = [];
let requestCounter = 0;
// HTTP-only browser QA lacks secure-context randomUUID; production Tauri has it.
if (!crypto.randomUUID) crypto.randomUUID = () => `00000000-0000-4000-8000-${(++requestCounter).toString(16).padStart(12, '0')}`;
window.__TAURI_INTERNALS__ = { invoke: async (command, { envelope }) => {
  if (command !== 'petrolab_command') throw new Error(command);
  const { command: operation, payload } = envelope;
  if (operation === 'formula.methods.list') return { result: data.catalog };
  if (operation === 'formula.preview') return { result: payload.parameters.fe_mode === 'all_fe2' ? data.preview : data.invalid };
  if (operation === 'formula.save') { runs = [{ run: data.saved.run }]; return { result: data.saved }; }
  if (operation === 'formula.runs.list') return { result: { runs } };
  throw new Error(operation);
} };

createRoot(document.getElementById('root')).render(<>
  <header style={{ padding: 12 }}>PetroLab · Формулы · синтетическая UI-проверка, без записи в проект</header>
  <MineralsWorkspace project={{ total: 1, analyses: [data.analysis], mineral_options: ['olivine'] }} databasePath="synthetic-qa"
    onRefresh={() => {}} onDecide={() => {}} onAddData={() => {}} />
</>);
