import { useMemo, useState } from "react";
import { ArrowLeft, CaretDown, CheckCircle, Columns, Database, DownloadSimple, File, FileArrowUp, FloppyDisk, GearSix, Info, MagnifyingGlass, Plus, Warning, X } from "@phosphor-icons/react";
import "./styles.css";

const sheets = [{ name: "Sheet1", state: "needs" }, { name: "Геохимия", state: "ready" }, { name: "19KL23", state: "needs" }, { name: "Data", state: "needs" }];
const rows = [["KL23-001","51.23","8.12","2.35","6.41","1.84","3.12","2.10","45"],["KL23-002","50.87","7.98","2.28","6.37","1.76","3.08","2.05","46"],["KL23-003","51.64","8.21","2.41","6.53","1.69","3.18","2.12","47"],["KL23-004","52.11","8.36","2.28","6.62","1.84","3.25","2.18","48"],["KL23-005","50.43","7.85","2.36","6.29","1.72","3.21","1.98","49"],["KL23-006","51.07","8.05","2.33","6.34","1.68","3.11","2.07","50"],["KL24-001","53.12","6.91","1.98","5.83","1.55","2.84","1.87","51"],["KL24-002","52.78","7.02","1.92","5.76","1.51","2.81","1.84","52"],["KL24-003","53.45","6.99","1.94","5.81","1.53","2.86","1.88","53"],["KL24-004","52.91","6.77","1.91","5.74","1.49","2.80","1.83","54"]];
const mappingSeed = [["Образец ID","Sample","ok"],["Кремнезём %","SiO₂ (мас. %)","ok"],["Железо общее","FeOt (мас. %)","warning"],["Магний %","MgO (мас. %)","ok"],["Кальций %","CaO (мас. %)","ok"],["Натрий %","Na₂O (мас. %)","ok"],["Калий %","K₂O (мас. %)","ok"],["Потери при прокаливании %","ППП (мас. %)","ok"],["Grain #","Grain","ok"]];
const fields = ["Sample","SiO₂ (мас. %)","FeOt (мас. %)","MgO (мас. %)","CaO (мас. %)","Na₂O (мас. %)","K₂O (мас. %)","ППП (мас. %)","Grain","Не импортировать"];
const navigation = [[MagnifyingGlass,"Поиск"],[FileArrowUp,"Импорт"],[Database,"Анализы"],[Columns,"Образцы"],[Columns,"Минералы"],[Columns,"Связи"],[File,"Изображения"],[Columns,"Построение"],[Columns,"Статистика"],[Columns,"Публикации"]];

export function App() {
  const [activeSheet, setActiveSheet] = useState("Sheet1");
  const [headerRow, setHeaderRow] = useState("2–3 (многострочный заголовок)");
  const [dataStart, setDataStart] = useState("4");
  const [mappings, setMappings] = useState(mappingSeed.map((item) => [...item]));
  const [allRows, setAllRows] = useState(false);
  const [toast, setToast] = useState("");
  const selectedCount = useMemo(() => sheets.filter((sheet) => sheet.name === activeSheet || sheet.state === "ready").length, [activeSheet]);
  const updateMapping = (index, value) => setMappings((items) => items.map((item, current) => current === index ? [item[0], value, item[2]] : item));
  const saveDraft = () => { setToast("Черновик импорта сохранён локально"); window.setTimeout(() => setToast(""), 2600); };
  return <main className="app-shell">
    <aside className="sidebar"><div className="brand"><div className="brand-mark"><Database size={30} weight="duotone" /></div><div><strong>PetroLab</strong><span>Локальная версия 1.6.2</span></div></div><nav>{navigation.map(([Icon,label]) => <button className={label === "Импорт" ? "nav-item active" : "nav-item"} key={label}><Icon size={19}/><span>{label}</span></button>)}</nav><div className="side-footer"><Info size={18}/><span>Импорт: проверка до записи</span></div></aside>
    <section className="workspace"><header className="topbar"><div><p><b>Проект:</b> Северный массив</p><p><b>Направление импорта:</b> Табличный импорт <CaretDown size={14}/></p></div><div className="top-actions"><span>Сохранено: сегодня, 10:24</span><button className="outline-button"><DownloadSimple size={18}/> Импорт <CaretDown size={14}/></button><button className="icon-button"><GearSix size={21}/></button><button className="icon-button"><X size={21}/></button></div></header>
      <div className="stepper">{[["1","Файл",true],["2","Листы и колонки",false],["3","Минералы и образцы",false],["4","Проверка",false]].map(([number,label,done],index) => <div className="step" key={label}><div className={index === 1 ? "step-number current" : done ? "step-number done" : "step-number"}>{done ? <CheckCircle size={22} weight="fill"/> : number}</div><span>{label}</span>{index < 3 && <i/>}</div>)}</div>
      <section className="import-panel"><div className="instruction"><Info size={20} weight="fill"/><div><b>Выберите листы для импорта и сопоставьте колонки с полями PetroLab.</b><span>Строки с данными начинаются после заголовков. Заголовки могут быть в нескольких строках.</span></div></div>
        <div className="import-grid"><aside className="sheet-list"><h3>Листы в файле Excel</h3>{sheets.map((sheet) => <button key={sheet.name} onClick={() => setActiveSheet(sheet.name)} className={activeSheet === sheet.name ? "sheet-card selected" : "sheet-card"}><File size={22}/><span><b>{sheet.name}</b><small>{sheet.state === "ready" ? <><CheckCircle size={15} weight="fill"/> Готов к импорту</> : <><Warning size={15} weight="fill"/> Требуется настройка</>}</small></span></button>)}<div className="sheet-summary">Выбрано листов: {selectedCount} из 4</div><button className="wide-outline">Выбрать все</button></aside>
          <section className="preview"><div className="preview-title"><h3>Предпросмотр листа: <b>{activeSheet}</b></h3></div><div className="warning-banner"><Warning size={24} weight="fill"/><div><b>Найдены блоки образцов без колонки Sample</b><span>В листе обнаружены блоки, которые не содержат колонки Sample.</span></div><button className="mini-outline">Использовать как образцы</button><button className="mini-outline">Проверить вручную</button></div><div className="table-controls"><label>Строка заголовков:<select value={headerRow} onChange={(event) => setHeaderRow(event.target.value)}><option>2–3 (многострочный заголовок)</option><option>2</option><option>3</option></select></label><label>Начальная строка данных:<select value={dataStart} onChange={(event) => setDataStart(event.target.value)}><option>4</option><option>5</option></select></label><label className="checkbox"><input type="checkbox" checked={allRows} onChange={(event) => setAllRows(event.target.checked)}/> Показывать все строки</label></div>
            <div className="data-table"><table><thead><tr><th></th>{["A","B","C","D","E","F","G","H","I"].map((letter) => <th key={letter}>{letter}</th>)}</tr><tr><th></th>{["Образец","Кремнезём","Железо","Магний","Кальций","Натрий","Калий","Потери при прокаливании","Grain #"].map((name) => <th key={name}>{name}<small>{name === "Образец" ? "ID" : name === "Grain #" ? "" : "%"}</small></th>)}</tr></thead><tbody><tr className="group"><td></td><td colSpan="9">19KL23</td></tr>{rows.slice(0,6).map((row,index) => <tr key={index}><td>{index + 4}</td>{row.map((value,cell) => <td key={cell}>{value}</td>)}</tr>)}<tr className="group"><td></td><td colSpan="9">19KL24</td></tr>{rows.slice(6,allRows ? 10 : 8).map((row,index) => <tr key={index}><td>{index + 11}</td>{row.map((value,cell) => <td key={cell}>{value}</td>)}</tr>)}</tbody></table></div><div className="table-note">Показано строк: {allRows ? "10" : "8"} из 412 <span><Info size={18}/> Блоки (19KL23, 19KL24) не являются данными - это заголовки образцов.</span></div></section>
          <aside className="mapping"><h3>Сопоставление колонок</h3>{mappings.map(([label,value,state],index) => <label className={state === "warning" ? "mapping-row needs" : "mapping-row"} key={label}><span>{label}</span><b>→</b><select value={value} onChange={(event) => updateMapping(index,event.target.value)}>{fields.map((field) => <option key={field}>{field}</option>)}</select>{state === "warning" ? <Warning size={20} weight="fill"/> : <CheckCircle size={20} weight="fill"/>}{state === "warning" && <small>Требуется подтверждение</small>}</label>)}<h4>Неизвестные колонки (пользовательские поля)</h4>{[1,2,3].map((number) => <div className="custom-field" key={number}><span>Пользовательское поле {number}</span><select><option>Нет</option><option>Сохранить как примечание</option></select><X size={16}/></div>)}<button className="wide-outline"><Plus size={18}/> Добавить пользовательское поле</button><p className="mapping-help"><Info size={18}/> Сопоставьте колонки перед переходом к следующему шагу.</p></aside></div>
        <div className="recipe-summary"><File size={35} weight="thin"/><div><b>Каждый лист будет импортирован отдельно</b><span>Для каждого выбранного листа будет создан свой рецепт импорта.</span></div><div className="chips">{sheets.map((sheet) => <span key={sheet.name}><CheckCircle size={15}/> {sheet.name}</span>)}</div></div></section>
      <footer className="import-footer"><button className="outline-button">Отмена</button><div><button className="outline-button"><ArrowLeft size={17}/> Назад</button><button className="primary-button" onClick={saveDraft}>Далее: минералы и образцы <ArrowLeft className="right-arrow" size={18}/></button></div></footer>{toast && <div className="toast"><FloppyDisk size={20} weight="fill"/> {toast}</div>}</section></main>;
}
